services:
  - type: web
    name: discovery-service
    runtime: docker
    dockerContext: backend
    dockerfilePath: discovery-service/Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8761"

  - type: web
    name: api-gateway
    runtime: docker
    dockerContext: backend
    dockerfilePath: api-gateway/Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka/
      - key: ALLOWED_ORIGINS
        sync: false

  - type: web
    name: product-service
    runtime: docker
    dockerContext: backend
    dockerfilePath: product-service/Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8081"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka/
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: localhost:9092

  - type: web
    name: user-service
    runtime: docker
    dockerContext: backend
    dockerfilePath: user-service/Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8082"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka/
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

  - type: web
    name: order-service
    runtime: docker
    dockerContext: backend
    dockerfilePath: order-service/Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8083"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka/
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
